package SoseL21.runtime.worksheets;

/*Generated by MPS */


public class WorksheetImpl {
  private static int a1;
  private static boolean b1;
  private static int c1;

  private static int a2;
  private static int c2;
  private static boolean b2;

}
