package SoseL21.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BoolVar = 0;
  public static final int IntVar = 1;
  public static final int RefVar = 2;
  public static final int Statement = 3;
  public static final int Variable = 4;
  public static final int Worksheet = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc905bbb1e30c4548L, 0x898343d4ffd2305cL);
    builder.put(0x78ee936948184adfL, BoolVar);
    builder.put(0x78ee936948184ab6L, IntVar);
    builder.put(0x78ee936948184b06L, RefVar);
    builder.put(0x78ee936948184a3fL, Statement);
    builder.put(0x78ee9369481a0bc2L, Variable);
    builder.put(0x78ee936948184a3aL, Worksheet);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
