package SoseL21.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBoolVar = createDescriptorForBoolVar();
  /*package*/ final ConceptDescriptor myConceptIntVar = createDescriptorForIntVar();
  /*package*/ final ConceptDescriptor myConceptRefVar = createDescriptorForRefVar();
  /*package*/ final ConceptDescriptor myConceptStatement = createDescriptorForStatement();
  /*package*/ final ConceptDescriptor myConceptVariable = createDescriptorForVariable();
  /*package*/ final ConceptDescriptor myConceptWorksheet = createDescriptorForWorksheet();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBoolVar, myConceptIntVar, myConceptRefVar, myConceptStatement, myConceptVariable, myConceptWorksheet);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BoolVar:
        return myConceptBoolVar;
      case LanguageConceptSwitch.IntVar:
        return myConceptIntVar;
      case LanguageConceptSwitch.RefVar:
        return myConceptRefVar;
      case LanguageConceptSwitch.Statement:
        return myConceptStatement;
      case LanguageConceptSwitch.Variable:
        return myConceptVariable;
      case LanguageConceptSwitch.Worksheet:
        return myConceptWorksheet;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBoolVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "BoolVar", 0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184adfL);
    b.class_(false, false, false);
    b.super_("SoseL21.structure.Variable", 0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee9369481a0bc2L);
    b.parent(0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184a3fL);
    b.origin("r:f56d7ba5-9a84-425b-8c23-13d75958121a(SoseL21.structure)/8714064409398889183");
    b.version(2);
    b.property("value", 0x78ee936948184ae2L).type(PrimitiveTypeId.BOOLEAN).origin("8714064409398889186").done();
    b.alias("boolean");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "IntVar", 0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184ab6L);
    b.class_(false, false, false);
    b.super_("SoseL21.structure.Variable", 0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee9369481a0bc2L);
    b.parent(0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184a3fL);
    b.origin("r:f56d7ba5-9a84-425b-8c23-13d75958121a(SoseL21.structure)/8714064409398889142");
    b.version(2);
    b.property("value", 0x78ee936948184ab9L).type(PrimitiveTypeId.INTEGER).origin("8714064409398889145").done();
    b.alias("int");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRefVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "RefVar", 0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184b06L);
    b.class_(false, false, false);
    b.parent(0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184a3fL);
    b.origin("r:f56d7ba5-9a84-425b-8c23-13d75958121a(SoseL21.structure)/8714064409398889222");
    b.version(2);
    b.associate("target", 0x78ee936948184b0bL).target(0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee9369481a0bc2L).optional(false).origin("8714064409398889227").done();
    b.alias("ref");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "Statement", 0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184a3fL);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f56d7ba5-9a84-425b-8c23-13d75958121a(SoseL21.structure)/8714064409398889023");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVariable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "Variable", 0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee9369481a0bc2L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f56d7ba5-9a84-425b-8c23-13d75958121a(SoseL21.structure)/8714064409399004098");
    b.version(2);
    b.alias("var");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWorksheet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "Worksheet", 0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184a3aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f56d7ba5-9a84-425b-8c23-13d75958121a(SoseL21.structure)/8714064409398889018");
    b.version(2);
    b.aggregate("body", 0x78ee936948184a3dL).target(0xc905bbb1e30c4548L, 0x898343d4ffd2305cL, 0x78ee936948184a3fL).optional(true).ordered(true).multiple(true).origin("8714064409398889021").done();
    b.alias("Worksheet");
    return b.create();
  }
}
